export const metadata = {
    title: "About Dhanjyoti",
    description: "Generated by Dj",
}

export default function About(){
    return (
        <div>
            This is about!
        </div>
    )
}