import { Metadata } from 'next';

import '../style/globals.css';
export const metadata: Metadata = {
  title: {
    // absolute: "",
    default: "Next.js Dj",
    template: "%s | dhanjyoti rabha",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <header className="bg-blue-200 p-4">
          <p>Header</p>
        </header>
        <main className='h-[calc(100vh-110px)]'>
          {children}
        </main>
        <footer className="bg-slate-200 p-4">
          <p>Footer</p>
        </footer>
      </body>
    </html>
  );
}
